baseURL = 'my-industrie.eu'
languageCode = 'de-at'
title = 'INDustrie Gaming'
copyright = "© 2024 INDustrie Gaming"

[[menus.main]]
name = 'News'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Der Verein'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'Mitglied Werden'
url = "https://discord.com/channels/273205894072893440/972789343812993075"
weight = 30

[[menus.main]]
name = 'ProjektX LAN FAQ'
pageRef = '/projektx'
weight = 40

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[markup]
	[markup.goldmark]
	parser.attribute.block = true
	parser.attribute.title = true
